{% set name = "voluptuous-serialize" %}
{% set version = "2.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/voluptuous-serialize-{{ version }}.tar.gz
  sha256: 5359f2e0a4f972ae03066e0777b4f0755c9226b2af099ca4fc55432efd1a447b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - voluptuous

test:
  imports:
    - voluptuous_serialize
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/home-assistant-libs/voluptuous-serialize
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Experiment to convert voluptuous schemas to JSON
  description: |
    Convert Voluptuous schemas to dictionaries so they can be serialized.
  doc_url: https://github.com/home-assistant-libs/voluptuous-serialize
  dev_url: https://github.com/home-assistant-libs/voluptuous-serialize

extra:
  recipe-maintainers:
    - jan-janssen
