{% set name = "voluptuous-serialize" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/voluptuous-serialize-{{ version }}.tar.gz
  sha256: 79acdc58239582a393144402d827fa8efd6df0f5350cdc606d9242f6f9bca7c4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - voluptuous

test:
  imports:
    - voluptuous_serialize
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/home-assistant-libs/voluptuous-serialize
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Experiment to convert voluptuous schemas to JSON
  description: |
    Convert Voluptuous schemas to dictionaries so they can be serialized.
  doc_url: https://github.com/home-assistant-libs/voluptuous-serialize
  dev_url: https://github.com/home-assistant-libs/voluptuous-serialize

extra:
  recipe-maintainers:
    - jan-janssen
